#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
PROJECT_DIR=/home/jaroknor/NLeSC/InSilicoMeat/StirredTankModel
echo $PROJECT_DIR
# Copy flange surface from resources directory
cp $PROJECT_DIR/geometries/POC-spinnerflask.obj constant/geometry/

runApplication blockMesh
runApplication surfaceFeatures
runApplication snappyHexMesh -overwrite

#------------------------------------------------------------------------------
